filters:
        - filter_type: file
          source_file: doom/src/main/res/values/strings.xml
          file_format: ANDROID
          source_language: en
          translation_files_expression: 'doom/src/main/res/values-<lang>/strings.xml'